import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import nodemailer from 'nodemailer';
const app=express(),port=Number(process.env.PORT||4000);
app.use(cors({origin:process.env.CLIENT_ORIGIN||'http://localhost:5173'}));app.use(express.json({limit:'20kb'}));app.use('/api/contact',rateLimit({windowMs:900000,max:5,standardHeaders:true,legacyHeaders:false}));
app.get('/api/health',(_req,res)=>res.json({ok:true}));
app.post('/api/contact',async(req,res,next)=>{try{const{name,email,message}=req.body??{};if(typeof name!=='string'||name.trim().length<2||name.length>100||typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email)||typeof message!=='string'||message.trim().length<10||message.length>3000)return res.status(400).json({message:'Please provide a valid name, email, and message.'});const{SMTP_HOST,SMTP_PORT,SMTP_USER,SMTP_PASS,CONTACT_TO}=process.env;if(!SMTP_HOST||!SMTP_PORT||!SMTP_USER||!SMTP_PASS||!CONTACT_TO)return res.status(503).json({message:'Contact delivery is not configured yet.'});const transporter=nodemailer.createTransport({host:SMTP_HOST,port:Number(SMTP_PORT),secure:Number(SMTP_PORT)===465,auth:{user:SMTP_USER,pass:SMTP_PASS}});await transporter.sendMail({from:SMTP_USER,to:CONTACT_TO,replyTo:email.trim(),subject:`Portfolio message from ${name.trim()}`,text:`Name: ${name.trim()}\nEmail: ${email.trim()}\n\n${message.trim()}`});res.status(202).json({ok:true});}catch(error){next(error)}});
app.use((error,_req,res,_next)=>{console.error(error);res.status(500).json({message:'Unable to send your message right now.'})});app.listen(port,()=>console.log(`Portfolio API listening on ${port}`));
